"""add fks for audit_log

Revision ID: 3fa84f8bd512
Revises: 1013776c4826
Create Date: 2024-11-25 01:19:01.879234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa84f8bd512'
down_revision: Union[str, None] = '1013776c4826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('order_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index('idx_audit_logs_order_id', 'audit_logs', ['order_id'], unique=False, schema='public')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'audit_logs', 'orders', ['order_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', schema='public', type_='foreignkey')
    op.drop_index('idx_audit_logs_order_id', table_name='audit_logs', schema='public')
    op.drop_column('audit_logs', 'user_id')
    op.drop_column('audit_logs', 'order_id')
    # ### end Alembic commands ###
